[tool.poetry]
name = "2015"
version = "0.1.0"
description = ""
authors = ["onefastsnail"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
