name: "2016"

on:
  push:
    branches: [ "master" ]
    paths:
      - 2016/**

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./2016
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58

      - name: Test
        run: go test -v ./...